package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"goblin/internal/envs"
)

// esc is the ANSI escape byte written literally into generated scripts.
const esc = "\x1b"

func ansiOpen(code string) string { return esc + "[" + code + "m" }

const ansiReset = esc + "[0m"

// promptBadge is the coloured "(goblin:NAME)" marker shown in every shell.
func promptBadge(name string) string {
	return ansiOpen("1;32") + "(goblin:" + name + ")" + ansiReset + " "
}

// sanitizeName strips characters that would break a shell string literal.
func sanitizeName(name string) string {
	repl := strings.NewReplacer("'", "", `"`, "", "\n", "", "\r", "", "\\", "", "`", "")
	n := repl.Replace(name)
	if n == "" {
		n = "env"
	}
	return n
}

// shellLaunch describes how to start a shell so its prompt shows the badge.
type shellLaunch struct {
	argv     []string
	extraEnv []string
	cleanup  func()
}

// prepareShell builds the launch plan for shPath inside env. The prompt of
// the launched interactive shell is prefixed with a goblin badge; where the
// user already has a prompt, it is preserved and the badge is prepended.
func prepareShell(env *envs.Environment, shPath string) shellLaunch {
	name := sanitizeName(env.Name)
	base := filepath.Base(shPath)
	switch base {
	case "ravenshell", "rsh":
		return ravenLaunch(env, shPath, name)
	case "bash":
		return bashLaunch(env, shPath, name)
	case "zsh":
		return zshLaunch(env, shPath, name)
	case "fish":
		return fishLaunch(shPath, name)
	default:
		// POSIX sh (dash, ash, busybox) sources the file named by $ENV on
		// interactive startup; that is where PS1 must be set, as the plain
		// PS1 environment variable is reset by a non-login shell.
		envfile := filepath.Join(env.Root, "shell-init.sh")
		body := "# goblin shell prompt (generated)\n" +
			"PS1='" + promptBadge(name) + "$ '\n"
		_ = os.WriteFile(envfile, []byte(body), 0o644)
		return shellLaunch{
			argv:     []string{shPath},
			extraEnv: []string{"ENV=" + envfile, "PS1=" + promptBadge(name) + "$ "},
		}
	}
}

// ravenLaunch generates a RavenShell init script that keeps the user's
// existing prompt (RavenTerminal's Lang/VCS line, when present) and
// prepends the goblin badge, then points RAVEN_INIT_SCRIPT at it.
func ravenLaunch(env *envs.Environment, shPath, name string) shellLaunch {
	script := filepath.Join(env.Root, "shell-init.rsh")
	_ = os.WriteFile(script, []byte(genRavenInit(name)), 0o644)
	return shellLaunch{
		argv:     []string{shPath},
		extraEnv: []string{"RAVEN_INIT_SCRIPT=" + script},
	}
}

func genRavenInit(name string) string {
	badge := promptBadge(name)
	var b strings.Builder
	b.WriteString("# goblin shell prompt (generated by `goblin shell`; safe to delete).\n")

	prev := readPrevRavenInit()
	hasHelpers := prev != "" &&
		strings.Contains(prev, "__raven_cwd") &&
		strings.Contains(prev, "__raven_detect_lang") &&
		strings.Contains(prev, "__raven_detect_vcs")

	if hasHelpers {
		// Reuse the terminal's helper functions; our prompt() defined below
		// overrides its prompt() (later definition wins in RavenShell).
		b.WriteString("# --- begin inherited init ---\n")
		b.WriteString(prev)
		if !strings.HasSuffix(prev, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("# --- end inherited init ---\n")
		fmt.Fprintf(&b, `fn prompt(status) {
    line1 = "%s%s" + __raven_cwd() + "%s"
    line1 = line1 + " %s|%s %sLang:%s %s" + __raven_detect_lang() + "%s"
    line1 = line1 + " %s|%s %sVCS:%s %s" + __raven_detect_vcs() + "%s"
    line2 = "[%sgoblin%s] "
    if status != 0 {
        line2 = line2 + "%serr:" + status + "%s "
    }
    line2 = line2 + "%s>%s "
    return line1 + "\n" + line2
}
`,
			badge, ansiOpen("0;36"), ansiReset,
			ansiOpen("0;90"), ansiReset, ansiOpen("0;34"), ansiReset, ansiOpen("0;33"), ansiReset,
			ansiOpen("0;90"), ansiReset, ansiOpen("0;34"), ansiReset, ansiOpen("0;35"), ansiReset,
			ansiOpen("0;32"), ansiReset,
			ansiOpen("0;31"), ansiReset,
			ansiOpen("0;90"), ansiReset)
		return b.String()
	}

	// No inherited prompt: a compact badge + cwd prompt.
	fmt.Fprintf(&b, `fn prompt(status) {
    d = $(cwd)
    h = $HOME
    if d == h {
        d = "~"
    } else {
        d = replace(d, h + "/", "~/")
    }
    line = "%s%s" + d + "%s "
    if status != 0 {
        line = line + "%serr:" + status + "%s "
    }
    line = line + "%s>%s "
    return line
}
`,
		badge, ansiOpen("0;36"), ansiReset,
		ansiOpen("0;31"), ansiReset,
		ansiOpen("0;90"), ansiReset)
	return b.String()
}

// readPrevRavenInit returns the current RAVEN_INIT_SCRIPT contents, or "".
func readPrevRavenInit() string {
	path := os.Getenv("RAVEN_INIT_SCRIPT")
	if path == "" {
		return ""
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}

func bashLaunch(env *envs.Environment, shPath, name string) shellLaunch {
	rc := filepath.Join(env.Root, "shell-init.bash")
	body := "# goblin shell prompt (generated)\n" +
		"if [ -f \"$HOME/.bashrc\" ]; then . \"$HOME/.bashrc\"; fi\n" +
		"PS1='\\[" + esc + "[1;32m\\](goblin:" + name + ")\\[" + esc + "[0m\\] '\"$PS1\"\n"
	_ = os.WriteFile(rc, []byte(body), 0o644)
	return shellLaunch{argv: []string{shPath, "--rcfile", rc, "-i"}}
}

func zshLaunch(env *envs.Environment, shPath, name string) shellLaunch {
	dir := filepath.Join(env.Root, "zdotdir")
	_ = os.MkdirAll(dir, 0o755)
	home, _ := os.UserHomeDir()
	body := "# goblin shell prompt (generated)\n" +
		"[ -n \"$GOBLIN_ZDOTDIR_PREV\" ] && ZDOTDIR=\"$GOBLIN_ZDOTDIR_PREV\" || unset ZDOTDIR\n" +
		"[ -f \"" + home + "/.zshrc\" ] && source \"" + home + "/.zshrc\"\n" +
		"PROMPT='%F{green}(goblin:" + name + ")%f '$PROMPT\n"
	_ = os.WriteFile(filepath.Join(dir, ".zshrc"), []byte(body), 0o644)
	extra := []string{"ZDOTDIR=" + dir}
	if prev := os.Getenv("ZDOTDIR"); prev != "" {
		extra = append(extra, "GOBLIN_ZDOTDIR_PREV="+prev)
	}
	return shellLaunch{argv: []string{shPath}, extraEnv: extra}
}

func fishLaunch(shPath, name string) shellLaunch {
	init := "functions -q fish_prompt; and functions -c fish_prompt __goblin_orig_prompt; " +
		"function fish_prompt; set_color green; echo -n '(goblin:" + name + ") '; set_color normal; " +
		"if functions -q __goblin_orig_prompt; __goblin_orig_prompt; else; echo -n (prompt_pwd)' > '; end; end"
	return shellLaunch{argv: []string{shPath, "-C", init}}
}
